plugin:
    name: 'shohabbos.payme::lang.plugin.name'
    description: 'shohabbos.payme::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-paypal
    homepage: 'https://itmaker.uz'
permissions:
    manage_payme_settings:
        tab: 'shohabbos.payme::lang.plugin.name'
        label: 'Manage settings'
    manage_payme_transactions:
        tab: 'shohabbos.payme::lang.plugin.name'
        label: 'Manage transactions'
